### ISSUE TITLE
Feature Request: Reset form values when working with useSubmit

### ISSUE THREAD

**Issue by ibesoft11** [peternoordijk/preform#1]
Currently, there's a way to reset the values of form fields individually when using `useFormApi` but there's none for `useSubmit`.

Suggestion:
There should be a way to reset all the fields at once whether we're using `useSubmit` or `useFormApi`

**Comment by peternoordijk** [comment]
This has been fixed with version 0.1.6. You can now call `reset()` from the `useFormApi` response.
